name: my-streamlit-app
channels:
  - conda-forge
dependencies:
  - python=3.8  # or your specific Python version
  - cmake  # Add CMake for dlib installation
  - pip
  - pip:
      - torch
      - torch-geometric
      - streamlit
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - opencv-python-headless  # Use the headless version to avoid GUI issues
      - dlib
      - Pillow
