name: my-streamlit-app
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8  # or your specific Python version
  - pip
  - pytorch::pytorch  # Install PyTorch via conda's PyTorch channel
  - pip:
      - torch-geometric  # This will be installed via pip
      - streamlit
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - opencv-python-headless
      - dlib
      - Pillow
