name: my-streamlit-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # Specify your Python version
  - pip  # Make sure pip is installed
  - pip:
      - torch  # Install PyTorch via pip
      - torch-geometric
      - streamlit
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - opencv-python  # Install opencv-python via pip
      - dlib
      - Pillow
      - scikit-image  # Sometimes opencv-python requires this
