name: my-streamlit-app
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cmake  # Ensure CMake is available for dlib
  - pip
  - pip:
      - torch
      - torch-geometric
      - streamlit
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - opencv-python-headless
      - dlib
      - Pillow
  - cudatoolkit=none  # Ensures CUDA toolkit is not installed or attempted
