name: my-streamlit-app
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8  # or the version you are using
  - pip
  - pip:
      - torch
      - torch-geometric
      - streamlit
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - opencv-python
      - dlib
      - Pillow
